embedding_size: 64
feat_embed_dim: 64

n_mm_layers: 1
n_layers: 2
knn_k: 10
mm_image_weight: 0.1
learning_rate: [0.001, 0.0001]
reg_weight: [0.001]

#dropout: [0.3 0.5]
#dropout: [0.1, 0.3, 0.5, 0.7]
dropout: [0.5]

#mask_weight_g: [0.01, 0.001, 0]
weight_g: [0.01, 0.1, 0.2, 0.4, 0.6, 0.8, 1.0]

weight_cl: [0.01, 0.1, 0.2, 0.4, 0.6, 0.8, 1.0]

temp: [0.2, 0.4, 0.8]

hyper_parameters: ["reg_weight", "learning_rate", 'dropout',  'mask_weight_g',  'temp', 'cl_weight']
